services:
  db:
    image: postgres:17.2
    container_name: postgres_17_2
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'